### ISSUE TITLE
No way to stop calibration?

### ISSUE THREAD

**Issue by jfrux** [qdrk/fpvsim-timer-app#1] opened 2023-02-07 16:41 UTC

**Comment by qdrk** [comment] 2023-03-09 04:35
Thanks for flagging. I met this too, it's caused by unstable connection with the timer hardware. Did you use a router as bridge and use 5.8G Wifi?

**Comment by qdrk** [comment] 2023-06-16 05:37
FYI: this is fixed in the latest [2.2.0-rc5](https://github.com/qdrk/fpvsim-timer-app/releases/tag/2.2.0-rc5)

**Closed as completed by qdrk** 2023-06-16 05:37 UTC
